[package]
name = "ammonia-wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
ammonia = "4"
wasm-bindgen = "0.2"

[lib]
crate-type = ["cdylib"]

[dependencies.web-sys]
version = "0.3"
features = ["console"]

[dependencies.js-sys]
version = "0.3"
